name: paddle_ocr_native_example
description: Demonstrates offline OCR with paddle_ocr_native.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: 1.1.2
  paddle_ocr_native:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ocr_sample.png
